<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerVshrrh2\App_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerVshrrh2/App_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerVshrrh2.legacy');

    return;
}

if (!\class_exists(App_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerVshrrh2\App_KernelDevDebugContainer::class, App_KernelDevDebugContainer::class, false);
}

return new \ContainerVshrrh2\App_KernelDevDebugContainer([
    'container.build_hash' => 'Vshrrh2',
    'container.build_id' => 'de5f8337',
    'container.build_time' => 1762269625,
    'container.runtime_mode' => \in_array(\PHP_SAPI, ['cli', 'phpdbg', 'embed'], true) ? 'web=0' : 'web=1',
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerVshrrh2');
